[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "4mxrKT9nTNKSoH13CZXbZdx6qxH7jxANEQfQeXozv1pP"
anchor_vault_rc = "7FKaY8yTWT7mw3ef7WnnZUbgefef7Z3DoRt7896Njx9F"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --release -- --nocapture"

[hooks]
